[build]
  # Build command for the frontend with legacy peer deps
  command = "npm run build:netlify"
  
  # Directory to publish (where build output goes)
  publish = "dist/public"
  
  # Functions directory
  functions = "netlify/functions"
  
  # Set Node.js version
  [build.environment]
    NODE_VERSION = "20"
    NODE_ENV = "production"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# API function redirects - map API routes to Netlify Functions
[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/auth-register"
  status = 200

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth/me"
  to = "/.netlify/functions/auth-me"
  status = 200

[[redirects]]
  from = "/api/leads/export/csv"
  to = "/.netlify/functions/leads-export-csv"
  status = 200

[[redirects]]
  from = "/api/leads/:id/notes"
  to = "/.netlify/functions/leads-notes/:id"
  status = 200

[[redirects]]
  from = "/api/leads/:id"
  to = "/.netlify/functions/leads-detail/:id"
  status = 200

[[redirects]]
  from = "/api/leads"
  to = "/.netlify/functions/leads"
  status = 200

[[redirects]]
  from = "/api/reminders/:id/complete"
  to = "/.netlify/functions/reminders-complete/:id/complete"
  status = 200

[[redirects]]
  from = "/api/reminders/:id"
  to = "/.netlify/functions/reminders-detail/:id"
  status = 200

[[redirects]]
  from = "/api/reminders"
  to = "/.netlify/functions/reminders"
  status = 200

[[redirects]]
  from = "/api/activities"
  to = "/.netlify/functions/activities"
  status = 200

[[redirects]]
  from = "/api/analytics/metrics"
  to = "/.netlify/functions/analytics-metrics"
  status = 200

[[redirects]]
  from = "/api/analytics/leads-by-status"
  to = "/.netlify/functions/analytics-leads-by-status"
  status = 200

[[redirects]]
  from = "/api/analytics/leads-by-source"
  to = "/.netlify/functions/analytics-leads-by-source"
  status = 200

[[redirects]]
  from = "/api/analytics/conversion-trend"
  to = "/.netlify/functions/analytics-conversion-trend"
  status = 200

[[redirects]]
  from = "/api/analytics/metrics-trends"
  to = "/.netlify/functions/analytics-metrics-trends"
  status = 200

[[redirects]]
  from = "/api/analytics/monthly-metrics"
  to = "/.netlify/functions/analytics-monthly-metrics"
  status = 200

# Redirect all other routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables - Set these in your Netlify dashboard under Site settings > Environment variables
# 
# Required:
# MONGODB_URI = "your-mongodb-connection-string"
# JWT_SECRET = "your-jwt-secret" (optional - will use fallback if not set)